<a href="https://colab.research.google.com/github/amarchenac-ops/repositoryanthony/blob/main/%5B00%5D%20-%20Workshops/Workshop_ML_PartTime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Workshop Final — Machine Learning Integrado


## Contexto y objetivo

Este workshop plantea un **caso de negocio en retail**: una cadena de tiendas quiere entender mejor a sus clientes y optimizar sus decisiones comerciales. Para ello se pondrá en práctica todo el ciclo de Machine Learning.

**Dataset propuesto (opcional):** [Sample - Superstore (Kaggle)](https://www.kaggle.com/datasets/vivek468/superstore-dataset-final)  

[Dataset en GitHub (no requiere autenticación)](https://raw.githubusercontent.com/dtoralg/INESDI_Data-Science_ML_IA/main/%5B00%5D%20-%20Workshops/Sample%20-%20Superstore.csv)

- 9994 filas de datos de pedidos de una cadena de tiendas. Encoding latin1.
- Permite trabajar con problemas de **clasificación** (ej. clientes rentables vs. no rentables), **regresión** (predicción de ventas o beneficio) y **clustering** (segmentación de clientes).  

**Columnas principales:**  
- Order ID / Customer ID: identificadores únicos de pedido y cliente  
- Order Date / Ship Mode: fecha y modo de envío  
- Segment: tipo de cliente (Consumer, Corporate, Home Office)  
- Region / State / City: localización geográfica  
- Category / Sub-Category: categoría de producto  
- Sales: importe de la venta  
- Quantity: número de unidades vendidas  
- Discount: descuento aplicado (%)  
- Profit: beneficio asociado al pedido  

**Problema de negocio (ejemplo):**  
“Queremos identificar qué clientes tienen mayor probabilidad de generar pérdidas, predecir su volumen de compra y segmentarlos para diseñar campañas de marketing más eficaces.”

**Importante:**  
- Este dataset es una **base común** para quienes lo deseen.  
- Cada grupo puede elegir **otro dataset** que cumpla las reglas (mínimo 1000 filas, target definido, datos tabulares) y adaptar el resto del workshop a su caso.

## Pregunta de negocio

Redacta aquí en una frase la pregunta que guiará vuestro trabajo.

In [ ]:
# Qué problema (o problemas) de negocio quieres resolver?
# ¿Cuál es el jugador ideal para que represente la marca Revolut?

# Fase 1 - EDA y primeros modelos

In [2]:
# Imports - añade aquí las librerías que vayas a utilizar en el notebook

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
# etc

In [6]:
# Carga aquí tus datos - puedes elegir el dataset propuesto u otro de tu
# elección.
df = pd.read_csv('/content/jugadores_con_seguidores_rellenos.csv', sep=';')
df

,id_jugador,nombre,Nacionalidad,Seguidores Insta,Año de nacimiento,puesto,comienzo,valor,salario,clausula,...,Técnica,Inteligencia,Indice total deportivo,PAIS REVOLUT,LOGARITMO INSTAGRAM,NORM_PERF,NORM_SOCIAL,NORM_AUDIENCE,NORM_REPUTACION,NORM_COST
0,1723,R. Vata,Albania,24800,2005,MCO,16/7/2021,1500000,5000,3600000,...,62.56,156.4,101.89,0,4.394.469.192.347.430,0.257804,NaN,NaN,NaN,NaN
1,2179,M. Berisha,Albania,26400,2004,MC,18/8/2022,625000,2000,1500000,...,63.88,143.2,94.23,0,4.421.620.377.106.830,0.201700,NaN,NaN,NaN,NaN
2,2953,S. Shpendi,Albania,31200,2003,DC,5/8/2023,1200000,2000,2400000,...,60.69,133.2,89.79,0,4.494.168.513.490.300,0.169210,NaN,NaN,NaN,NaN
3,3336,A. Pajaziti,Albania,12400,2003,MCD,1/7/2019,1100000,9000,2300000,...,62.69,160.4,102.24,0,40.934.567.074.986.000,0.260369,NaN,NaN,NaN,NaN
4,23,L. Ben Farhat,Alemania,19500,2007,MD,9/3/2024,400000,500,890000,...,60.25,134.4,88.31,1,4.290.056.882.303.360,0.158384,NaN,NaN,NaN,0.002502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,675,J. Sabobo Banda,Zambia,8307,2006,MCO,16/1/2024,375000,500,919000,...,58.63,137.2,89.43,0,39.194.964.878.630.600,0.166576,NaN,NaN,NaN,NaN
2396,3665,K. Mutandwa,Zambia,3333,2003,DC,3/3/2024,240000,3000,480000,...,49.25,130.0,84.89,0,35.229.655.954.919.800,0.133377,NaN,NaN,NaN,NaN
2397,989,P. Madanha,Zimbabue,2592,2005,MD,10/12/2022,375000,500,544000,...,54.44,152.6,97.86,0,34.138.025.167.693.500,0.228279,NaN,NaN,NaN,NaN
2398,2755,T. Chirewa,Zimbabue,8972,2004,MD,18/9/2023,575000,6000,1500000,...,60.13,149.2,97.19,0,39.529.376.677.509.800,0.223372,NaN,NaN,NaN,NaN
2399,3274,T. Maswanhise,Zimbabue,20653,2003,MD,1/7/2021,1200000,7000,2900000,...,66.81,151.8,99.85,0,43.150.041.726.848.900,0.242856,NaN,NaN,NaN,NaN

## Fase 1.1: EDA y preparación de datos

1. Descripción del dataset y justificación de su elección  
2. Identificación de variables, tipos, nulos y duplicados  
3. Limpieza de datos  
4. Creación de nuevas variables (feature engineering)  
5. Transformaciones: encoding y escalado  
6. Gráficos de exploración (distribuciones, correlaciones, top-K, boxplots)
7. Explicaciones y decisiones en función de los resultados (punto de vista de negocio)

In [8]:
# Desarrolla tu código de EDA y preparación de datos
columnas_a_eliminar = ['NORM_SOCIAL', 'NORM_AUDIENCE', 'NORM_REPUTACION', 'NORM_COST']
df_limpio = df.drop(columns=columnas_a_eliminar, errors='ignore')
df_limpio

,id_jugador,nombre,Nacionalidad,Seguidores Insta,Año de nacimiento,puesto,comienzo,valor,salario,clausula,...,pase,regates_reflejos,fisico,Performance físico,Técnica,Inteligencia,Indice total deportivo,PAIS REVOLUT,LOGARITMO INSTAGRAM,NORM_PERF
0,1723,R. Vata,Albania,24800,2005,MCO,16/7/2021,1500000,5000,3600000,...,54,70,53,68.54,62.56,156.4,101.89,0,4.394.469.192.347.430,0.257804
1,2179,M. Berisha,Albania,26400,2004,MC,18/8/2022,625000,2000,1500000,...,59,58,63,59.31,63.88,143.2,94.23,0,4.421.620.377.106.830,0.201700
2,2953,S. Shpendi,Albania,31200,2003,DC,5/8/2023,1200000,2000,2400000,...,46,64,58,61.00,60.69,133.2,89.79,0,4.494.168.513.490.300,0.169210
3,3336,A. Pajaziti,Albania,12400,2003,MCD,1/7/2019,1100000,9000,2300000,...,59,61,65,64.23,62.69,160.4,102.24,0,40.934.567.074.986.000,0.260369
4,23,L. Ben Farhat,Alemania,19500,2007,MD,9/3/2024,400000,500,890000,...,58,62,42,54.92,60.25,134.4,88.31,1,4.290.056.882.303.360,0.158384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,675,J. Sabobo Banda,Zambia,8307,2006,MCO,16/1/2024,375000,500,919000,...,50,60,41,56.54,58.63,137.2,89.43,0,39.194.964.878.630.600,0.166576
2396,3665,K. Mutandwa,Zambia,3333,2003,DC,3/3/2024,240000,3000,480000,...,40,53,60,60.38,49.25,130.0,84.89,0,35.229.655.954.919.800,0.133377
2397,989,P. Madanha,Zimbabue,2592,2005,MD,10/12/2022,375000,500,544000,...,48,56,70,68.31,54.44,152.6,97.86,0,34.138.025.167.693.500,0.228279
2398,2755,T. Chirewa,Zimbabue,8972,2004,MD,18/9/2023,575000,6000,1500000,...,52,60,55,64.92,60.13,149.2,97.19,0,39.529.376.677.509.800,0.223372
2399,3274,T. Maswanhise,Zimbabue,20653,2003,MD,1/7/2021,1200000,7000,2900000,...,56,63,47,63.62,66.81,151.8,99.85,0,43.150.041.726.848.900,0.242856

In [19]:
df_limpio.head()

,id_jugador,nombre,Nacionalidad,Seguidores Insta,Año de nacimiento,puesto,comienzo,valor,salario,clausula,...,pase,regates_reflejos,fisico,Performance físico,Técnica,Inteligencia,Indice total deportivo,PAIS REVOLUT,LOGARITMO INSTAGRAM,NORM_PERF
0,1723,R. Vata,Albania,24800,2005,MCO,16/7/2021,1500000,5000,3600000,...,54,70,53,68.54,62.56,156.4,101.89,0,4.394.469.192.347.430,0.257804
1,2179,M. Berisha,Albania,26400,2004,MC,18/8/2022,625000,2000,1500000,...,59,58,63,59.31,63.88,143.2,94.23,0,4.421.620.377.106.830,0.201700
2,2953,S. Shpendi,Albania,31200,2003,DC,5/8/2023,1200000,2000,2400000,...,46,64,58,61.00,60.69,133.2,89.79,0,4.494.168.513.490.300,0.169210
3,3336,A. Pajaziti,Albania,12400,2003,MCD,1/7/2019,1100000,9000,2300000,...,59,61,65,64.23,62.69,160.4,102.24,0,40.934.567.074.986.000,0.260369
4,23,L. Ben Farhat,Alemania,19500,2007,MD,9/3/2024,400000,500,890000,...,58,62,42,54.92,60.25,134.4,88.31,1,4.290.056.882.303.360,0.158384

In [20]:
df_limpio.isnull().sum()

id_jugador                0
nombre                    0
Nacionalidad              0
Seguidores Insta          0
Año de nacimiento         0
puesto                    0
comienzo                  0
valor                     0
salario                   0
clausula                  0
TOTAL SPONSORSHIP COST    0
centros                   0
definicion                0
precision_cabeza          0
pases_cortos              0
voleas                    0
tecnica                   0
regates                   0
efecto                    0
precision_faltas          0
pases_largos              0
control_balon             0
movimiento                0
aceleracion               0
velocidad                 0
agilidad                  0
reflejos                  0
equilibrio                0
potencia                  0
salto                     0
resistencia               0
fuerza                    0
tiros_lejanos             0
mentalidad                0
agresividad               0
intercepciones            0
vision                    0
penaltis                  0
compostura                0
pie_malo                  0
filigranas                0
ritmo                     0
tiros                     0
pase                      0
regates_reflejos          0
fisico                    0
Performance físico        0
Técnica                   0
Inteligencia              0
Indice total deportivo    0
PAIS REVOLUT              0
LOGARITMO INSTAGRAM       0
NORM_PERF                 0
dtype: int64

In [22]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 53 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_jugador              2400 non-null   int64
 1   nombre                  2400 non-null   object
 2   Nacionalidad            2400 non-null   object
 3   Seguidores Insta        2400 non-null   int64
 4   Año de nacimiento       2400 non-null   int64
 5   puesto                  2400 non-null   object
 6   comienzo                2400 non-null   object
 7   valor                   2400 non-null   int64
 8   salario                 2400 non-null   int64
 9   clausula                2400 non-null   int64
 10  TOTAL SPONSORSHIP COST  2400 non-null   int64
 11  centros                 2400 non-null   int64
 12  definicion              2400 non-null   int64
 13  precision_cabeza        2400 non-null   int64
 14  pases_cortos            2400 non-null   int64
 15  voleas                  2400 non-null   int64
 16  tecnica                 2400 non-null   int64
 17  regates                 2400 non-null   int64
 18  efecto                  2400 non-null   int64
 19  precision_faltas        2400 non-null   int64
 20  pases_largos            2400 non-null   int64
 21  control_balon           2400 non-null   int64
 22  movimiento              2400 non-null   int64
 23  aceleracion             2400 non-null   int64
 24  velocidad               2400 non-null   int64
 25  agilidad                2400 non-null   int64
 26  reflejos                2400 non-null   int64
 27  equilibrio              2400 non-null   int64
 28  potencia                2400 non-null   int64
 29  salto                   2400 non-null   int64
 30  resistencia             2400 non-null   int64
 31  fuerza                  2400 non-null   int64
 32  tiros_lejanos           2400 non-null   int64
 33  mentalidad              2400 non-null   int64
 34  agresividad             2400 non-null   int64
 35  intercepciones          2400 non-null   int64
 36  vision                  2400 non-null   int64
 37  penaltis                2400 non-null   int64
 38  compostura              2400 non-null   int64
 39  pie_malo                2400 non-null   int64
 40  filigranas              2400 non-null   int64
 41  ritmo                   2400 non-null   int64
 42  tiros                   2400 non-null   int64
 43  pase                    2400 non-null   int64
 44  regates_reflejos        2400 non-null   int64
 45  fisico                  2400 non-null   int64
 46  Performance físico      2400 non-null   float64
 47  Técnica                 2400 non-null   float64
 48  Inteligencia            2400 non-null   float64
 49  Indice total deportivo  2400 non-null   float64
 50  PAIS REVOLUT            2400 non-null   int64
 51  LOGARITMO INSTAGRAM     2400 non-null   object
 52  NORM_PERF               2400 non-null   float64
dtypes: float64(5), int64(43), object(5)
memory usage: 993.9+ KB

In [23]:
import datetime

# 1. ROI Social (Seguidores por cada euro de salario)
df_limpio['ROI_SOCIAL'] = df_limpio['Seguidores Insta'] / df_limpio['salario'].replace(0, 1)

# 2. Calcular Edad (Variable auxiliar necesaria)
anio_actual = datetime.datetime.now().year
df_limpio['EDAD'] = anio_actual - df_limpio['Año de nacimiento']

# 3. Ratio Técnica vs Físico
df_limpio['RATIO_TECNICO_FISICO'] = df_limpio['Técnica'] / df_limpio['Performance físico'].replace(0, 1)

# 4. Eficiencia de Costo (Costo por cada punto de índice deportivo)
df_limpio['COSTO_POR_CALIDAD'] = df_limpio['valor'] / df_limpio['Indice total deportivo'].replace(0, 1)

# 5. Clasificación de Potencial (Lógica de experto)
def clasificar_potencial(row):
    if row['EDAD'] <= 23 and row['Indice total deportivo'] >= 75:
        return 'Promesa Elite'
    elif row['EDAD'] <= 23 and row['Indice total deportivo'] < 75:
        return 'Joven en Desarrollo'
    else:
        return 'Jugador Consolidado'

df_limpio['CATEGORIA_POTENCIAL'] = df_limpio.apply(clasificar_potencial, axis=1)

print("Variables estratégicas añadidas con éxito.")
display(df_limpio[['nombre', 'ROI_SOCIAL', 'EDAD', 'COSTO_POR_CALIDAD', 'CATEGORIA_POTENCIAL']].head())

Variables estratégicas añadidas con éxito.

          nombre  ROI_SOCIAL  EDAD  COSTO_POR_CALIDAD CATEGORIA_POTENCIAL
0        R. Vata    4.960000    21       14721.758759       Promesa Elite
1     M. Berisha   13.200000    22        6632.707206       Promesa Elite
2     S. Shpendi   15.600000    23       13364.517207       Promesa Elite
3    A. Pajaziti    1.377778    23       10758.998435       Promesa Elite
4  L. Ben Farhat   39.000000    19        4529.498358       Promesa Elite

In [24]:
df_limpio

,id_jugador,nombre,Nacionalidad,Seguidores Insta,Año de nacimiento,puesto,comienzo,valor,salario,clausula,...,Inteligencia,Indice total deportivo,PAIS REVOLUT,LOGARITMO INSTAGRAM,NORM_PERF,ROI_SOCIAL,EDAD,RATIO_TECNICO_FISICO,COSTO_POR_CALIDAD,CATEGORIA_POTENCIAL
0,1723,R. Vata,Albania,24800,2005,MCO,16/7/2021,1500000,5000,3600000,...,156.4,101.89,0,4.394.469.192.347.430,0.257804,4.960000,21,0.912752,14721.758759,Promesa Elite
1,2179,M. Berisha,Albania,26400,2004,MC,18/8/2022,625000,2000,1500000,...,143.2,94.23,0,4.421.620.377.106.830,0.201700,13.200000,22,1.077053,6632.707206,Promesa Elite
2,2953,S. Shpendi,Albania,31200,2003,DC,5/8/2023,1200000,2000,2400000,...,133.2,89.79,0,4.494.168.513.490.300,0.169210,15.600000,23,0.994918,13364.517207,Promesa Elite
3,3336,A. Pajaziti,Albania,12400,2003,MCD,1/7/2019,1100000,9000,2300000,...,160.4,102.24,0,40.934.567.074.986.000,0.260369,1.377778,23,0.976024,10758.998435,Promesa Elite
4,23,L. Ben Farhat,Alemania,19500,2007,MD,9/3/2024,400000,500,890000,...,134.4,88.31,1,4.290.056.882.303.360,0.158384,39.000000,19,1.097050,4529.498358,Promesa Elite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,675,J. Sabobo Banda,Zambia,8307,2006,MCO,16/1/2024,375000,500,919000,...,137.2,89.43,0,39.194.964.878.630.600,0.166576,16.614000,20,1.036965,4193.223750,Promesa Elite
2396,3665,K. Mutandwa,Zambia,3333,2003,DC,3/3/2024,240000,3000,480000,...,130.0,84.89,0,35.229.655.954.919.800,0.133377,1.111000,23,0.815667,2827.188126,Promesa Elite
2397,989,P. Madanha,Zimbabue,2592,2005,MD,10/12/2022,375000,500,544000,...,152.6,97.86,0,34.138.025.167.693.500,0.228279,5.184000,21,0.796955,3832.004905,Promesa Elite
2398,2755,T. Chirewa,Zimbabue,8972,2004,MD,18/9/2023,575000,6000,1500000,...,149.2,97.19,0,39.529.376.677.509.800,0.223372,1.495333,22,0.926217,5916.246527,Promesa Elite
2399,3274,T. Maswanhise,Zimbabue,20653,2003,MD,1/7/2021,1200000,7000,2900000,...,151.8,99.85,0,43.150.041.726.848.900,0.242856,2.950429,23,1.050141,12018.027041,Promesa Elite

In [ ]:
# Desarrolla tu código de Clasificación

## Fase 1.3: Regresión

1. Selección del target numérico
2. Entrenamiento de un primer modelo + cálculo de métricas
3. Gráficas clave (visualización de predicciones)
4. Entrenamiento de un segundo modelo + cálculo de métricas
5. Gráficas clave segundo modelo (visualización de predicciones)
6. Comparativa de métricas
7. Explicación: cuál eliges y por qué

In [ ]:
# Desarrolla tu código de Regresión

## Fase 1.4: PCA y No Supervisados

1. Aplicación de PCA
2. Visualización de la reducción de dimensiones
3. Interpretación de los componentes principales
4. Selección de un modelo no supervisado (KMeans, DBSCAN o LOF)
5. Entrenamiento del modelo seleccionado
6. Visualización de resultados (clusters o anomalías)
7. Cálculo de métricas si aplica
8. Interpretación de resultados desde un punto de vista de negocio

Explicación: qué patrones se han descubierto y qué implicaciones tendría para negocio

In [ ]:
# Desarrolla tu código de PCA y No Supervisados

----

## 🔒 FASE 2 — Se desbloquea en Semana 2 (solo entonces editar esta parte)


## Contexto y objetivo

Una vez llegados aquí, podríamos seguir el ejercicio por dos vias.


**Vía 1:**  
Clasificación: Cliente rentable vs no rentable ( Profit > 0 )

**Vía 2:**  
Regresión: Predicción del profit

**Vía 3::**  
Calcular ambos tipos de modelos.


Para no hacer el ejercicio muy largo optaremos por la vía 2, predicción del profit, dejamos como opcional la vía 1.

# Fase 2 - Elección razonada del modelo

Antes de entrenar cualquier modelo, un buen científico de datos **justifica su elección**. Esta reflexión es clave en proyectos reales: los stakeholders querrán saber por qué usamos un algoritmo concreto.

### ¿Por qué modelos basados en árboles para predecir el Profit?

| Criterio | Situación en nuestro dataset | Ventaja de los árboles |
|----------|------------------------------|------------------------|
| **Relaciones no lineales** | Descuento alto → Profit negativo de forma no lineal | Los árboles capturan estas curvas sin transformaciones |
| **Interacciones entre variables** | Categoría + Descuento → Profit muy diferente | Los árboles modelan interacciones automáticamente |
| **Variables mixtas** | Numéricas (Sales) y categóricas codificadas | No requieren escalado ni normalización |
| **Outliers en el target** | Profit tiene valores extremos (pérdidas y ganancias grandes) | Más robustos que la regresión lineal |
| **Interpretabilidad** | El negocio quiere entender qué impulsa el beneficio | Feature importance + SHAP |

In [ ]:
# Qué modelo creeis que funcionará mejor con estos datos y porqué.
# ---

**✍️ Si no tienes claro que modelo es el mejor, saltate este apartado y completalo al final de la sesión.:**

*(Vamos a hacer una propuesta interesante, vamos a probar diferentes modelos para decirdir con criterio)*

---
## Fase 2.1 - Decision Tree: El Baseline

Empezamos con el modelo más sencillo. Un árbol de decisión individual nos servirá como **línea base** (baseline): cualquier modelo más complejo deberá superarlo.

💡 **Analogía de negocio:** El árbol de decisión es como el proceso de aprobación manual de un crédito: el gestor sigue un formulario de preguntas fijas. Funciona, pero es rígido y fácil de engañar.

In [ ]:
#Pistas, recuerda tener cargadas todas las librerias
#!pip install xgboost shap --quiet

#import pandas as pd
#import numpy as np
#import matplotlib.pyplot as plt
#import matplotlib.ticker as mtick
#import seaborn as sns
#import warnings
#warnings.filterwarnings('ignore')

#from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
#from sklearn.preprocessing import LabelEncoder
#from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
#from sklearn.tree import DecisionTreeRegressor, export_text, plot_tree
#from sklearn.ensemble import RandomForestRegressor

#from xgboost import XGBRegressor

#import shap
#shap.initjs()

In [ ]:
# -------------------------------------------------------
# ENTRENAMIENTO — Decision Tree Regressor
# -------------------------------------------------------


#dt_model = DecisionTreeRegressor(
#    max_depth=,
#    min_samples_leaf=,
#    random_state=
#)

#dt_model.fit(X_train, y_train)

#dt_preds = dt_model.predict(X_test)

**✍️ Conclusiones sobre este modelo.

In [ ]:
#

---
## Fase 2.2 - Random Forest: Bagging

💡 **Analogía de negocio:** Es como pedir opinión a 200 asesores financieros independientes y hacer la media. Ninguno es perfecto, pero juntos son mucho más fiables que uno solo.

In [ ]:
# -------------------------------------------------------
# ENTRENAMIENTO — Random Forest Regressor
# -------------------------------------------------------

#rf_model = RandomForestRegressor(
#    n_estimators=...,
#    max_depth=....,
#    max_features=...,
#    n_jobs=....,
#    random_state=....
#)

#rf_model.fit(X_train, y_train)

#rf_preds = rf_model.predict(X_test)

**✍️ Conclusiones sobre este modelo.

In [ ]:
#

---
## Fase 2.3 - XGBoost: Boosting

💡 **Analogía de negocio:** En lugar de promediar opiniones (Random Forest), el equipo hace una **revisión por rondas**: en cada ronda analiza los casos donde se equivocó antes y manda al mejor especialista para corregirlos.

In [ ]:
# -------------------------------------------------------
# ENTRENAMIENTO — XGBoost Regressor
# -------------------------------------------------------


#xgb_model = XGBRegressor(
#    n_estimators=....,
#    max_depth=...,
#    learning_rate=...,
#    subsample=....,
#    colsample_bytree=...,
#    reg_alpha=....,
#    reg_lambda=...,
#    random_state=...,
#    verbosity=....
#)

#xgb_model.fit(X_train, y_train)

#xgb_preds = xgb_model.predict(X_test)

**✍️ Conclusiones sobre este modelo.

In [ ]:
#

---
## Fase 2.4 — Fine-tuning con GridSearchCV

💡 **Analogía de negocio:** Es como testear sistemáticamente distintas configuraciones de una campaña de marketing (audiencia × presupuesto × creatividad) y quedarte con la combinación que maximiza el ROI.

In [ ]:
# -------------------------------------------------------
# FINE-TUNING — GridSearchCV sobre XGBoost (Ejemplo sobre XGBoost, si has elegido otro, hazlo sobre tu elección)
# -------------------------------------------------------


#param_grid = {
#    'n_estimators'    : [200, 400],
#    'max_depth'       : [4, 6],
#    'learning_rate'   : [0.05, 0.1],
#    'subsample'       : [0.7, 0.9],
#    'colsample_bytree': [0.7, 1.0],
#}

#xgb_base = XGBRegressor(random_state=42, verbosity=0)

#grid_search = GridSearchCV(
#    estimator=xgb_base,
#    param_grid=param_grid,
#    scoring='neg_root_mean_squared_error',
#    cv=....,
#    n_jobs=.....,
#    verbose=....
#)

#grid_search.fit(X_train, y_train)

---
## Fase 2.5 — Explicabilidad con SHAP

💡 **Analogía:** SHAP es como el desglose de una factura. No te dice solo el total (la predicción), sino cuánto contribuye cada concepto (feature) al precio final.

| Gráfico SHAP | ¿Qué muestra? | ¿Para quién? |
|---|---|---|
| Summary plot | Impacto global de cada variable | Presentación a dirección |
| Waterfall | Explicación de una predicción individual | Análisis de un pedido concreto |
| Dependence plot | Relación variable↔SHAP | Equipos de negocio y pricing |

In [ ]:
# -------------------------------------------------------
# SHAP PLOT 1 — Summary Plot (visión global)
# -------------------------------------------------------

In [ ]:
# -------------------------------------------------------
# SHAP PLOT 2 — Waterfall: explicamos UN pedido concreto
# -------------------------------------------------------

In [ ]:
# -------------------------------------------------------
# SHAP PLOT 3 — Dependence Plot: efecto del Discount
# -------------------------------------------------------

**✍️ Reflexión SHAP (SOLUCIÓN):**

1. **Top 3 variables según SHAP:** .... Rellenar...

---
## Fase 2.5 — Conclusión y Recomendaciones de Negocio

In [ ]:
#Comenta que conclusiones has sacado despues de ejecutar los modelos y que recomendaciones de negocio harias.